id = "boschdoit"
name = "BoschDoIt"
description = "The open source coding agent."
version = "1.1.45"
schema_version = 1
authors = ["Anomaly"]
repository = "https://github.com/cobaohieu/boschdoit"

[agent_servers.boschdoit]
name = "BoschDoIt"
icon = "./icons/boschdoit.svg"

[agent_servers.boschdoit.targets.darwin-aarch64]
archive = "https://github.com/cobaohieu/boschdoit/releases/download/v1.1.45/boschdoit-darwin-arm64.zip"
cmd = "./boschdoit"
args = ["acp"]

[agent_servers.boschdoit.targets.darwin-x86_64]
archive = "https://github.com/cobaohieu/boschdoit/releases/download/v1.1.45/boschdoit-darwin-x64.zip"
cmd = "./boschdoit"
args = ["acp"]

[agent_servers.boschdoit.targets.linux-aarch64]
archive = "https://github.com/cobaohieu/boschdoit/releases/download/v1.1.45/boschdoit-linux-arm64.tar.gz"
cmd = "./boschdoit"
args = ["acp"]

[agent_servers.boschdoit.targets.linux-x86_64]
archive = "https://github.com/cobaohieu/boschdoit/releases/download/v1.1.45/boschdoit-linux-x64.tar.gz"
cmd = "./boschdoit"
args = ["acp"]

[agent_servers.boschdoit.targets.windows-x86_64]
archive = "https://github.com/cobaohieu/boschdoit/releases/download/v1.1.45/boschdoit-windows-x64.zip"
cmd = "./boschdoit.exe"
args = ["acp"]
